### ISSUE TITLE
About couchbase lite 2.0 (db13) exception

### ISSUE THREAD

**Issue by zhuangpeng** [couchbaselabs/mobile-training-todo#151] opened 2017-08-02 00:20 UTC
Environment：
couchbase 5.0 beta 2
sync-gateway: 1.5 - 447
couchbase lite: db13
issue:
I run the TODO android sample project,when I edit the list,the android program crashed, and throw a exception.
I think lists to map convert has error,how can I resovle this error?
![image](https://user-images.githubusercontent.com/14283213/28852386-48a5e368-775b-11e7-81ad-93b1d15c4550.png)
![image](https://user-images.githubusercontent.com/14283213/28852395-565660d2-775b-11e7-888e-572c984d6f02.png)

**Comment by hideki** [comment] 2017-09-08 00:29
I tried to reproduce this issue with DB016. But the issue is no longer reproducible. I assume the issue was fixed in the previous DB builds.

**Closed by hideki** 2017-09-08 00:29 UTC
Labels: bug
